# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: '**'

env:
  LCOV_PATH: .build/artifacts/info.lcov
  BUILD_FOLDER: .build/debug/ParameterizedTestingPackageTests.xctest/Contents/MacOS/ParameterizedTestingPackageTests
  PROFDATA_FOLDER: .build/debug/codecov/default.profdata

jobs:
  build:

    runs-on: macos-12

    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: swift build

      - name: Run tests
        run: |
          swift test --enable-code-coverage
          xcrun llvm-cov report $BUILD_FOLDER -instr-profile $PROFDATA_FOLDER
          xcrun llvm-cov export -format="lcov" $BUILD_FOLDER -instr-profile $PROFDATA_FOLDER > $LCOV_PATH

      - name: Determine coverage
        uses: codecov/codecov-action@v3.1.1
